services:
  - type: web
    name: wixyeez-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wixyeez-db
          property: connectionString

databases:
  - name: wixyeez-db
    plan: free
